"""Add trade review fields

Revision ID: 10ff2958bc1e
Revises: 
Create Date: 2025-05-14 00:54:24.968316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ff2958bc1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_date', sa.DateTime(), nullable=True, comment='复盘日期'))
        batch_op.add_column(sa.Column('execution_quality', sa.Integer(), nullable=True, comment='执行质量评分(1-10)'))
        batch_op.add_column(sa.Column('psychology_state', sa.String(length=50), nullable=True, comment='交易心理状态'))
        batch_op.add_column(sa.Column('market_condition', sa.String(length=50), nullable=True, comment='市场条件'))
        batch_op.add_column(sa.Column('lessons_learned', sa.Text(), nullable=True, comment='经验教训'))
        batch_op.add_column(sa.Column('improvement_points', sa.Text(), nullable=True, comment='改进点'))
        batch_op.add_column(sa.Column('trade_screenshots', sa.Text(), nullable=True, comment='交易截图路径（多个路径用逗号分隔）'))
        batch_op.add_column(sa.Column('review_status', sa.String(length=20), nullable=True, comment='复盘状态(pending/completed)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('review_status')
        batch_op.drop_column('trade_screenshots')
        batch_op.drop_column('improvement_points')
        batch_op.drop_column('lessons_learned')
        batch_op.drop_column('market_condition')
        batch_op.drop_column('psychology_state')
        batch_op.drop_column('execution_quality')
        batch_op.drop_column('review_date')

    # ### end Alembic commands ###
